Improve parameters for operators #329
IPVS-AS/MBP pull request #476
Opened 2020-10-02 08:33 UTC by marvin21

Displaying of the 'device_code' parameter now depends on the settings. If a secured broker with OAuth2 is used, the device_code parameter is displayed when a new operator is added. Otherwise, this parameter is not visible.

Every time the operators list is loaded, the settings are requested from the backend. If the broker location in the settings equals 'LOCAL_SECURE' or 'REMOTE_SECURE', then the 'device_code' parameter is displayed. 

Resolves #329

2020-10-07 21:28 UTC, ana-silva commented
Unfortunately, the `Extraction/Control operators` and `Monitoring Operators` views are broken for a **non-admin** user.

The following appears only by an non-admin user:
![grafik](https://user-images.githubusercontent.com/17008080/95389213-c6c7f380-08f3-11eb-91ae-98d1b5446363.png)

The following occurs for **both** admin and non-admin user:
![grafik](https://user-images.githubusercontent.com/17008080/95389395-0d1d5280-08f4-11eb-8145-7eb76bbec452.png)

2020-10-07 21:32 UTC, ana-silva requested changes
The problems mentioned in the comments need to be solved.

2020-10-12 09:36 UTC, marvin21 commented
This occurs, because a non-admin user cannot access the secured settings endpoint. However, there is no other possibility to retrieve the current settings to be able to hide the parameters in new operators.
To fix it, the reading of the settings could be opened to be accessed by all logged in users. 
Is this a possible solution or should the retrieval of the settings remain restricted to only admin users?

2021-01-13 01:44 UTC, schneijan commented
Fixed in branch `first_release_fixes`. I guess the PR can be closed.

2021-01-13 17:05 UTC, closed without merging