Implement option to allow dynamic SSH ports through the API
IPVS-AS/MBP pull request #595
Opened 2021-06-15 18:53 UTC by c-mueller

Adjusting the SSH Port on creation of a device is mandatory, In order to implement integration tests with mocked IoT devices for the MBP application, according to our testing concept, since multiple mocked devices will potentially run on the same machine. 

This change introduces an Optional `port` field in the DeviceDTO if it is not set (i.e. `null`). It has also been ensured, that a unset Port in the database is automatically set to the Default (Port 22). Validation has also been implemented, the `port` parameter must be in the interval of 1 to 65535 or null so that the default can be used.

The following operations have been checked and they still seem to operate as expected:
- API Create Device with no port set
- Create through the WebUI with no port set (defaults to 22, as expected)
- A SSH connection is established with a modified port.

@T-Haller has also added the setters for the DTOs in order to get write access to them for testing.

<details>
  <summary>Invocation Notice</summary>
  Perfoming the following API Call (assuming you are Authenticated):
```
curl -X POST "http://localhost/api/devices" -H  "accept: application/hal+json" -H  "Content-Type: application/json" -d "{  \"componentType\": \"Computer\",  \"ipAddress\": \"10.133.1.8\",  \"name\": \"Archie Mock\",  \"password\": \"password\",  \"port\": 2222,  \"username\": \"mbp\"}"
```

Returns
```json
{
  "defaultEntity": false,
  "accessControlPolicyIds": [],
  "created": 1623782029253,
  "lastModified": 1623782029253,
  "id": "60c8f28d6f1deb7a7faf78bd",
  "name": "Archie Mock",
  "componentType": "Computer",
  "ipAddress": "10.133.1.8",
  "port": 2222,
  "date": "2021-06-15T18:33:49.250251",
  "username": "mbp",
  "entityType": "REQUESTED_ENTITY",
  "usesPassword": true,
  "usesRSAKey": false,
  "wasModelled": false,
  "ownerName": "admin",
  "_links": {
    "self": {
      "href": "http://localhost/60c8f28d6f1deb7a7faf78bd"
    }
  }
}
```
</details>

2021-06-18 16:16 UTC, schneijan requested changes

2021-06-18 16:18 UTC, schneijan commented
Would be great if you could move the validation logic into the device validator.

Btw, the DTO's are supposed to be read-only, so they do not really need the setters. ;-)

2021-06-23 14:19 UTC, c-mueller commented
Alright, the valdiation has been adjusted.

Regarding the setters:
We will use them to construct  objects containing data for the Implementation of tests. Without setters, or a parameterized constructor this is not possible on Private fields without using reflection which comes with a whole different set of problems.

To give an example:
Lets say we want to implement a test to create a device, the goal of this test is to test the overall functionality. 
To make this easy we want to create a `DeviceDTO`, with proper values, which is then Marshalled to JSON using the ObjectMapper. The Resulting json object is then sent to the Application using the HTTP endpoint (or a mocked version of it).

This way, changing a name in the device DTO does not affect the test, if renaming is done using an IDE. This is one of the benefits of testing like this.

2021-07-05 00:39 UTC, schneijan approved these changes
Alright, thanks a lot for the PR and the detailed explaination! I originally thought that you aimed to do the testing solely through the REST API via external clients, so that's the reason why I wondered about the setters. Now it's clear to me  :-)

2021-07-05 07:13 UTC, merged